// <auto-generated />
namespace Terabyte.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class rt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rt));
        
        string IMigrationMetadata.Id
        {
            get { return "201904102038489_rt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
